coreos/init

- scripts/issuegen
Avoids DNS lookup which may hang for a few seconds, avoids misleading
unknown_domain, avoids bogus output when the hostname is actually set to
the fully qualified domain name.
> issuegen: remove DNS domain name from issue

- systemd/system/issuegen.service
if issuegen doesn't wait for sshd-keygen to complete, issuegen will
sometimes display empty ssh host keys.
fixes coreos/bugs#106
> issuegen: add explicit dependency on sshd-keygen.service

- systemd/system/boot.automount
- systemd/system/boot.mount
- systemd/system/local-fs.target.wants/boot.automount
We need to mount the EFI system partition for updates so we can drop the
new kernel into it.
> Set up an automounter for /boot

- Makefile
- configs/logrotate.conf
- systemd/system/logrotate.service
- systemd/system/logrotate.timer
- systemd/system/multi-user.target.wants/logrotate.timer
The only two system logs that should need rotation by default are btmp
and wtmp, everything else is in the journal. btmp in particular is
likely to become huge due to the oodles of ssh brute-force bots.
> logrotate: add config and systemd units for logrotate

- systemd/system-generators/coreos-autologin-generator
If your system has somehow managed to wind up with / mounted read-only
when booting, coreos.autologin will fail because /tmp isn't yet a tmpfs,
and the bash script uses heredoc which creates temp files.
> coreos-autologin-generator: set TMPDIR to /run

- scripts/motdgen
as #182, but avoids the `wc -l` entirely, because the read builtin by itself is sufficient to determine whether the file is nonempty.
> remove some useless use of cat (alt)

- bin/coreos-install
this is trivial and self-explanatory I think
> coreos-install: fix outdated comment after 0664539

- scripts/motdgen
- systemd/system/motdgen.timer
- systemd/system/multi-user.target.wants/motdgen.timer
This removes the systemctl invocations from motdgen and their associated
output.  Maintaining these were what necessitated the motdgen.timer
unit, and we'll instead move this into the core user's login session
startup scripts.
Fixes https://github.com/coreos/bugs/issues/47
> motdgen: simplify motdgen and remove timer unit

- scripts/extend-filesystems
Hi,
this should fix coreos/bugs#1037.
It's kind of a "hotfix" so if there's a proper way of fixing this let me know.
Thanks!
> extend-filesystems script: fix raid device name when using HP Smart Array CCISS driver

- systemd/network/98-virtio.link
- udev/rules.d/79-net-google-compat.rules
In order to decouple the upgrade of systemd from the tricky migration of
network device names this new rule preserves the previous behavior.
Fixes https://github.com/coreos/bugs/issues/1168
TODO: need to build and test on GCE which has it's own mess
> network: disable new persistent style names for virtio devices

- bin/coreos-install
There has been a reported instance of coreos-install downloading the
disk image of 899.15.0 and the signature of 899.17.0, resulting in a
GPG verification failure. This mismatch is due to the fact that our
storage (currently Google Storage) is free to replicate things as slowly
as it would like. In this case, the signature (much smaller) replicated
faster than the disk image.
> coreos-install: resolve "current" version

- bin/coreos-install
This doesn't actually change the output, so it wasn't broken before.
> coreos-install: fix a couple of typos

- systemd/system/sshd-keygen.service
It is not valid to have a restart policy for one shots. We probably
don't want this to retry anyway - we'd rather figure out why it's
failing in the first place.
> systemd: remove restart policy from sshd-keygen

- systemd/network/yy-pxe.network
This fixes coreos/bugs#1432.  I've booted CoreOS with coreos.oem=pxe while dumping the network traffic, and the DHCP client identifier is the MAC address.
> network: set ClientIdentifier=mac for the PXE OEM

- bin/coreos-install
I tested this using zfs-fuse on Fedora.  It reproduced the error reliably, installing over disk images that I had set up with:
sudo zpool create zpool raidz1 $PWD/hd[a-c].img
This fixes coreos/bugs#1398.
> coreos-install: wipe labels at the end of the disk

- systemd/network/yy-pxe.network
Using the MAC as the client identifier is needed when the machine-id is
transient. This almost always happens when the root filesystem is not
disk-backed (PXE booting). It's more accurate to check that the 'root'
kernel parameter is not specified, in which case a tmpfs will be
created.
> network: change pxe network config condition

- .travis.yml
Looks like this flag was removed:
The command "pip install -r tests/requirements.txt --use-mirrors"
failed and exited with 2
> test: fix travis builds

- systemd/system/mdmonitor.service.d/00-syslog.conf
> systemd: use syslog by default for mdmonitor.service

- bin/coreos-install
Adds a new `-B` option to support installs for different CoreOS boards.
> add -B option to coreos-install

- bin/coreos-install
Commit 563ea0488b96eccab257c2287566c50f51e547fa (PR #228) introduced a problem on systems where no `/usr/share/coreos/release` file is present as the script aborts with a gawk *cannot open file* error.
```bash
root@rescue:~# ./coreos-install -d /dev/sda -C stable -c ./cloud-config.yaml
gawk: fatal: cannot open file `/usr/share/coreos/release' for reading (No such file or directory)
```
This fix introduces a simple check for file presence before feeding it to gawk. If the gawk step is skipped a default value (`amd64-usr`) will be assigned to `BOARD` anyway.
> check if coreos release file exists before getting BOARD

- systemd/system/motdgen.service
This reverts commit 5dcf1ab5e84204df5a5281f9e229ee379280d8f5.
This has the potential to cause a deadlock since this unit wedges itself
between locksmith starting and the user sessions starting. Since the
reboot strategy isn't even shown in the MOTD anymore (it's in the
profile), just drop this ordering.
> Revert "feat(motdgen): Ensure that motdgen runs after locksmith starts"

- bin/coreos-install
Since May 2014 our installation documentation has claimed that `coreos-install -C <channel>` is the way to install the latest version in `<channel>`. However, ever since the -C option was first implemented, -C has not overridden a defaulted -V. Thus the documented command only ever worked in the following cases:
1. coreos-install was run on a non-CoreOS host (so we didn't inherit a version from `os-release`).
2. The host was on the desired channel (so -C was redundant and the defaulted version existed in that channel). We would succeed but not necessarily install the latest version.
3. The host was on a different channel, but the host's version was also available in the desired channel due to bit-for-bit promotion. Again we wouldn't necessarily get the latest version.
Otherwise it failed …
> coreos-install: If -C is specified without -V, assume "-V current"

- bin/coreos-install
It previously set TMPDIR, but we no longer put anything large in there.  Drop the option for simplicity, but continue to respect TMPDIR just in case.
> coreos-install: Make -t option a no-op

- bin/coreos-install
Create a new routine default_board(), move the existing
/usr/share/coreos/release processing into default_board()
and add some new logic that uses 'uname -m' to guess a
default.
When run on other OSs using uname will give a default of
arm64-usr on arm64 machines.
> coreos-install: Use uname to get board default

- bin/coreos-install
After rereading the partition table, we weren't waiting for udev before trying to mount `ROOT` or `OEM`. That didn't matter if `${DEVICE}` was e.g. `/dev/sda`, since the partition device nodes would be created
by devtmpfs, but if `${DEVICE}` was a `/dev/disk` symlink, we'd try to access the partition symlink before udev got around to creating it and the mount would fail.
> coreos-install: Fix mounting filesystems through /dev/disk links

- systemd/network/yy-oracle-oci-bm.network
- systemd/network/yy-oracle-oci.network
Set `CriticalConnection` on all interfaces, since one of them will be used for root-on-iSCSI and we don't know which.
Disable `UseMTU` on non-virtualized NICs to fix https://github.com/coreos/bugs/issues/2031.
> network: add units for Oracle OCI

- tests/install_test.go
- tests/negative/disk_size.go
- tests/positive/general.go
- tests/register/register.go
- tests/registry/registry.go
- tests/util/util.go
Also adds support for local image file caching. The `UseLocalServer` flag can be used to pull from the local HTTP server.
------------
Adds flags to the Test object for the following options:
- Disk Size
* Size of the disk the image is being installed onto. Defaults to 10Gb
- Board
- LocalImage
- Version
- BaseURL
- Channel
- UseLocalServer
------------
The following tests have switched to pulling from the local HTTP server:
- TestCoreosInstall/Ignition_Test
- TestCoreosInstall/CloudConfig_Test
- TestCoreosInstall/Disk_Size_too_small_-_Remote
------------
The following tests are added in this PR:
- TestCoreosInstall/Disk_Size_too_small_-_Local
- TestCoreosInstall/Disk_Size_too_small_-_Remote
- TestCoreosInstall/Alpha_1520.0
- TestCoreosInstall/Channel_Only
- …
> tests: expand coreos-install test options

- tests/coreos-install/install_test.go
- tests/coreos-install/register/register.go
Individual tests should not be setting them.
cc @arithx
> tests/coreos-install: move runner-provided fields to a separate struct

- test
- tests/coreos-install/positive/general.go
- tests/coreos-install/register/register.go
Adds the OEM flag to the test object and the following new tests:
- TestCoreosInstall/OEM_-_ami
- TestCoreosInstall/OEM_-_cloudstack
- TestCoreosInstall/OEM_-_digitalocean
- TestCoreosInstall/OEM_-_packet
- TestCoreosInstall/OEM_-_rackspace
- TestCoreosInstall/OEM_-_vmware_raw
- TestCoreosInstall/OEM_-_xen
> tests/coreos-install: add oem flag & tests

- .gitignore
- test
- tests/coreos-install/install_test.go
- tests/coreos-install/positive/general.go
- tests/coreos-install/register/register.go
- tests/coreos-install/util/util.go
Updates the local HTTP server & file cache to attempt to detect
the version, board & channel of the host machine if it is
Container Linux before defaulting back to current, amd64-usr,
stable respectively. This mirrors the functionality present in
the coreos-install script.
---------
Adds the following flag onto the Test object:
- NetworkUnits
Adds the following tests:
- TestCoreosInstall/Network_Units_Test
---------
Also updates the test file to add the ability to compile the tests
via setting the variable `ACTION` to `COMPILE`, this is useful for
running the tests on a Container Linux machine, as you can
generate a compiled test file inside of a docker container with go
and then run them natively.
> tests/coreos-install: add network units flag + test

- systemd/system/boot.mount
- systemd/system/usr-share-oem.mount
Addresses https://github.com/coreos/bugs/issues/2245.
> systemd: fsck EFI-SYSTEM and OEM; drop unnecessary OEM mount option

- configs/sshd_config
Openssh 7.6 removes support for UsePrivilegeSeperation. Remove this from
our config to silence warnings about it.
> configs/sshd_config: remove deprecated option

- systemd/network/yy-azure-sriov.network
The kernel will automatically bond it to the synthetic interface, so ensure networkd doesn't try to configure it separately.
> network: ignore Azure SR-IOV VF interface

- systemd/network/yy-oracle-oci.network
Fixed upstream in systemd/systemd@e1c42e1b4097d575d8ac2222b2cc656fa256166b.
> network: drop obsolete comment

- bin/coreos-install
`install_from_url` returns as soon as all image data has been accepted by the page cache (modulo the pipe buffer size) but `write_to_disk` doesn't return until after the page cache has been flushed to disk. For e.g. slow USB devices, the interval between the two can be longer than five minutes. Increase the `wait_for_disk` timeout to two hours, which should hopefully trigger only in pathological cases.
> coreos-install: increase wait_for_disk timeout

- bin/coreos-install
Output the usage message after all the command line options are
processed so the user specified options will show as the 'default'
values.  This will allow the user to confirm the options are correct
before doing the install by running the script with the -h option.
Also, print the default value for all options, and, for consistency,
add a period to the end of some usage lines.
> coreos-install: Cleanup usage message

- Makefile
- udev/bin/cloud_aws_ebs_nvme_id
- udev/rules.d/90-cloud-storage.rules
Ref: https://github.com/coreos/bugs/issues/2399
Note: while this is AWS-specific, the payload is so small and the lack of updates for OEM partition scares me, so I'm proposing to add it here instead of a new OEM-specific ebuild.
> udev: add support for AWS EBS NVMe friendly names
